# Generated by Django 5.0.2 on 2024-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/796d02684eadafba407faf81a4fd697d.png', null=True, upload_to='users/', verbose_name='аватар'),
        ),
    ]
