# Generated by Django 5.0.2 on 2024-03-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Изменение статуса публикации'), ('set_description', 'Изменение описания продукта'), ('set_category', 'Изменение категории продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
